# Generated by Django 3.1.4 on 2021-08-21 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
